# Generated by Django 4.1.7 on 2023-02-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Пиццерия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('url', models.URLField(verbose_name='Сайт пиццерии')),
            ],
            options={
                'verbose_name': 'Пиццерия',
                'verbose_name_plural': 'Пиццерии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=32, verbose_name='Название пиццы')),
                ('short_description', models.CharField(max_length=64, verbose_name='Краткое описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('pizzashop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.pizzashop')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['pizza_name'],
            },
        ),
    ]
